// Manually curated list of iconic/well-known MTG cards
// A card is "iconic" if a typical experienced MTG player would recognize it by name
// This replaces the algorithmic popularity_score for the iconic tier

export const ICONIC_CARDS: string[] = [
  // Power 9
  "Black Lotus", "Ancestral Recall", "Time Walk", "Mox Pearl", "Mox Sapphire",
  "Mox Jet", "Mox Ruby", "Mox Emerald", "Timetwister",

  // Iconic banned/restricted cards
  "Balance", "Channel", "Fastbond", "Library of Alexandria", "Necropotence",
  "Demonic Tutor", "Vampiric Tutor", "Mystical Tutor", "Enlightened Tutor",
  "Worldly Tutor", "Sol Ring", "Mana Vault", "Mana Crypt", "Mana Drain",
  "Force of Will", "Griselbrand", "Tinker", "Tolarian Academy",
  "Yawgmoth's Will", "Mind's Desire", "Time Vault", "Skullclamp",
  "Umezawa's Jitte", "Stoneforge Mystic", "Jace, the Mind Sculptor",
  "Oko, Thief of Crowns", "Uro, Titan of Nature's Wrath",
  "Lurrus of the Dream-Den", "Ragavan, Nimble Pilferer",
  "The One Ring", "Treasure Cruise", "Dig Through Time",
  "Gitaxian Probe", "Mental Misstep", "Deathrite Shaman",
  "Splinter Twin", "Birthing Pod", "Hogaak, Arisen Necropolis",
  "Emrakul, the Aeons Torn", "Emrakul, the Promised End",
  "Sensei's Divining Top", "Contract from Below",

  // Classic creatures everyone knows
  "Serra Angel", "Shivan Dragon", "Birds of Paradise", "Llanowar Elves",
  "Elvish Mystic", "Dark Confidant", "Tarmogoyf", "Snapcaster Mage",
  "Delver of Secrets // Insectile Aberration", "Monastery Swiftspear",
  "Goblin Guide", "Wild Nacatl", "Vendilion Clique",
  "Thalia, Guardian of Thraben", "Mother of Runes",
  "Stoneforge Mystic", "True-Name Nemesis",
  "Craterhoof Behemoth", "Avenger of Zendikar",
  "Primeval Titan", "Sun Titan", "Grave Titan", "Inferno Titan",
  "Wurmcoil Engine", "Blightsteel Colossus",
  "Solemn Simulacrum", "Eternal Witness",
  "Sakura-Tribe Elder", "Scavenging Ooze",
  "Knight of the Reliquary", "Troll Ascetic",
  "Hypnotic Specter", "Royal Assassin", "Sengir Vampire",
  "Lord of Atlantis", "Goblin Warchief",
  "Bloodbraid Elf", "Kitchen Finks",
  "Thragtusk", "Siege Rhino", "Collected Company",
  "Bonecrusher Giant // Stomp", "Brazen Borrower // Petty Theft",
  "Questing Beast", "Elder Gargaroth",
  "Dryad of the Ilysian Grove", "Courser of Kruphix",
  "Phyrexian Obliterator", "Niv-Mizzet, Parun",
  "Kiki-Jiki, Mirror Breaker", "Zealous Conscripts",
  "Restoration Angel", "Flickerwisp",
  "Blood Artist", "Zulaport Cutthroat",
  "Viscera Seer", "Carrion Feeder",
  "Walking Ballista", "Hangarback Walker",
  "Thought-Knot Seer", "Reality Smasher",
  "Adeline, Resplendent Cathar", "Esper Sentinel",
  "Ragavan, Nimble Pilferer", "Dragon's Rage Channeler",
  "Ledger Shredder", "Murktide Regent",
  "Orcish Bowmasters", "Sheoldred, the Apocalypse",
  "Atraxa, Praetors' Voice", "Korvold, Fae-Cursed King",
  "Muldrotha, the Gravetide", "Edgar Markov",
  "Golos, Tireless Pilgrim", "Kenrith, the Returned King",
  "Etali, Primal Storm",

  // Iconic instants
  "Lightning Bolt", "Counterspell", "Swords to Plowshares",
  "Path to Exile", "Fatal Push", "Thoughtseize", "Inquisition of Kozilek",
  "Brainstorm", "Ponder", "Preordain", "Opt", "Consider",
  "Serum Visions", "Sleight of Hand",
  "Force of Will", "Force of Negation", "Daze", "Spell Pierce",
  "Mana Leak", "Remand", "Negate", "Dovin's Veto",
  "Cryptic Command", "Archmage's Charm",
  "Lightning Helix", "Boros Charm", "Abrupt Decay", "Assassin's Trophy",
  "Beast Within", "Generous Gift", "Chaos Warp", "Swords to Plowshares",
  "Chain Lightning", "Shock", "Burst Lightning", "Incinerate",
  "Terminate", "Drown in the Loch",
  "Dark Ritual", "Cabal Ritual", "Entomb", "Reanimate",
  "Vampiric Tutor", "Demonic Tutor",
  "Heroic Intervention", "Teferi's Protection",
  "Deflecting Swat", "Fierce Guardianship", "Deadly Rollick",
  "Flawless Maneuver",
  "Chord of Calling", "Collected Company",
  "Growth Spiral", "Explore",
  "Crop Rotation", "Harrow",
  "Swan Song", "An Offer You Can't Refuse",
  "Rapid Hybridization", "Pongify",
  "Dismember", "Go for the Throat",
  "Condemn", "Dispatch",
  "Repeal", "Cyclonic Rift",
  "Fact or Fiction", "Gifts Ungiven",
  "Faithless Looting", "Frantic Search",
  "High Tide", "Gush",
  "Snuff Out", "Massacre",
  "Hymn to Tourach", "Duress",

  // Iconic sorceries
  "Wrath of God", "Damnation", "Day of Judgment", "Supreme Verdict",
  "Blasphemous Act", "Toxic Deluge", "Farewell",
  "Cultivate", "Kodama's Reach", "Rampant Growth", "Farseek",
  "Nature's Lore", "Three Visits", "Skyshroud Claim",
  "Demonic Tutor", "Diabolic Intent",
  "Living Death", "Victimize", "Persist", "Exhume",
  "Vindicate", "Maelstrom Pulse", "Vandalblast",
  "Gamble", "Wheel of Fortune", "Windfall",
  "Thoughtseize", "Inquisition of Kozilek",
  "Ponder", "Preordain", "Gitaxian Probe",
  "Green Sun's Zenith", "Natural Order",
  "Show and Tell", "Sneak Attack",
  "Armageddon", "Jokulhaups",
  "Time Warp", "Temporal Manipulation",
  "Expressive Iteration",

  // Iconic enchantments
  "Rhystic Study", "Smothering Tithe", "Mystic Remora",
  "Sylvan Library", "Phyrexian Arena",
  "Doubling Season", "Parallel Lives",
  "Animate Dead", "Necromancy", "Dance of the Dead",
  "Ghostly Prison", "Propaganda", "Sphere of Safety",
  "Blood Moon", "Back to Basics", "Stasis",
  "Necropotence", "Yawgmoth's Bargain",
  "Opposition", "Recurring Nightmare",
  "Bitterblossom", "Shark Typhoon",
  "The Great Henge", "Guardian Project",
  "Hardened Scales", "Doubling Season",
  "Land Tax", "Burgeoning",
  "Wild Growth", "Utopia Sprawl",
  "Omniscience", "Dream Halls",
  "Thassa, God of the Sea", "Erebos, God of the Dead",
  "Purphoros, God of the Forge", "Nylea, God of the Hunt",
  "Heliod, Sun-Crowned",
  "Impact Tremors",
  "Rest in Peace", "Leyline of the Void",

  // Iconic artifacts
  "Sol Ring", "Arcane Signet", "Mana Crypt", "Mana Vault",
  "Chrome Mox", "Mox Diamond", "Mox Opal", "Mox Amber",
  "Lotus Petal", "Lotus Bloom", "Lion's Eye Diamond",
  "Lightning Greaves", "Swiftfoot Boots", "Basilisk Collar",
  "Sword of Fire and Ice", "Sword of Feast and Famine",
  "Batterskull", "Umezawa's Jitte",
  "Aether Vial", "Chalice of the Void", "Ensnaring Bridge",
  "Crucible of Worlds", "Chromatic Lantern",
  "Thought Vessel", "Mind Stone", "Fellwar Stone",
  "Commander's Sphere", "Thran Dynamo", "Gilded Lotus",
  "Everflowing Chalice",
  "Cranial Plating", "Springleaf Drum",
  "Oblivion Stone", "Nevinyrral's Disk",
  "Sensei's Divining Top", "Scroll Rack",
  "Isochron Scepter", "Panharmonicon",
  "Ashnod's Altar", "Phyrexian Altar",
  "Skullclamp", "Grafdigger's Cage", "Tormod's Crypt",
  "Nihil Spellbomb", "Soul-Guide Lantern", "Relic of Progenitus",
  "Pithing Needle", "Sorcerous Spyglass",
  "The Rack", "Black Vise",
  "Winter Orb", "Static Orb", "Trinisphere",
  "Tangle Wire", "Smokestack",
  "Sword of the Animist",
  "Solemn Simulacrum", "Wurmcoil Engine",
  "Hangarback Walker", "Walking Ballista",
  "The One Ring",

  // Iconic planeswalkers
  "Jace, the Mind Sculptor", "Jace, Vryn's Prodigy // Jace, Telepath Unbound",
  "Liliana of the Veil", "Liliana, the Last Hope",
  "Karn Liberated", "Karn, the Great Creator",
  "Ugin, the Spirit Dragon",
  "Teferi, Time Raveler", "Teferi, Hero of Dominaria",
  "Oko, Thief of Crowns",
  "Wrenn and Six", "Wrenn and Realmbreaker",
  "Garruk Wildspeaker",
  "Chandra, Torch of Defiance",
  "Nissa, Who Shakes the World",
  "Elspeth, Sun's Champion", "Elspeth, Knight-Errant",
  "Gideon, Ally of Zendikar",
  "Narset, Parter of Veils",
  "Dack Fayden",
  "Nicol Bolas, Dragon-God",
  "Ashiok, Dream Render",

  // Iconic lands
  // Fetchlands
  "Flooded Strand", "Polluted Delta", "Bloodstained Mire",
  "Wooded Foothills", "Windswept Heath",
  "Scalding Tarn", "Misty Rainforest", "Verdant Catacombs",
  "Arid Mesa", "Marsh Flats",
  // Shocklands
  "Hallowed Fountain", "Watery Grave", "Blood Crypt",
  "Stomping Ground", "Temple Garden",
  "Godless Shrine", "Steam Vents", "Overgrown Tomb",
  "Sacred Foundry", "Breeding Pool",
  // Classic duals (not in DB but just in case)
  "Tundra", "Underground Sea", "Badlands", "Taiga", "Savannah",
  "Scrubland", "Volcanic Island", "Bayou", "Plateau", "Tropical Island",
  // Other iconic lands
  "Command Tower", "Exotic Orchard", "City of Brass", "Mana Confluence",
  "Cavern of Souls", "Ancient Tomb", "Strip Mine", "Wasteland",
  "Urborg, Tomb of Yawgmoth", "Cabal Coffers",
  "Yavimaya, Cradle of Growth",
  "Boseiju, Who Endures", "Otawara, Soaring City",
  "Bojuka Bog", "Reliquary Tower", "Rogue's Passage",
  "Field of the Dead", "Dark Depths",
  "Maze of Ith", "Kor Haven", "Karakas",
  "Phyrexian Tower", "Gaea's Cradle", "Serra's Sanctum",
  "Mishra's Factory", "Mutavault", "Creeping Tar Pit",
  "Celestial Colonnade", "Raging Ravine",
  "Fabled Passage", "Prismatic Vista",
  "Evolving Wilds", "Terramorphic Expanse",
  "Path of Ancestry", "Myriad Landscape",
  "Ghost Quarter", "Tectonic Edge",
  "Urza's Saga",
  "Gemstone Caverns",
  "Reflecting Pool",
  // Painlands
  "Adarkar Wastes", "Underground River", "Sulfurous Springs",
  "Karplusan Forest", "Brushland", "Caves of Koilos",
  "Shivan Reef", "Llanowar Wastes", "Battlefield Forge",
  "Yavimaya Coast",
  // Fastlands
  "Seachrome Coast", "Darkslick Shores", "Blackcleave Cliffs",
  "Copperline Gorge", "Razorverge Thicket",
  // Checklands
  "Glacial Fortress", "Drowned Catacomb", "Dragonskull Summit",
  "Rootbound Crag", "Sunpetal Grove",
  "Isolated Chapel", "Sulfur Falls", "Woodland Cemetery",
  "Clifftop Retreat", "Hinterland Harbor",
  // Temples
  "Temple of Enlightenment", "Temple of Deceit", "Temple of Malice",
  "Temple of Abandon", "Temple of Plenty",
  "Temple of Silence", "Temple of Epiphany", "Temple of Mystery",
  "Temple of Triumph", "Temple of the False God",
  // Signet lands
  "Command Tower", "Exotic Orchard",

  // Iconic "fun" cards / memes
  "Chaos Orb", "Shahrazad", "Falling Star",
  "Storm Crow", "Colossal Dreadmaw",
  "Meandering Towershell",
  "One with Nothing",

  // Commander staples everyone knows
  "Cyclonic Rift", "Rhystic Study", "Smothering Tithe",
  "Dockside Extortionist", "Jeska's Will",
  "Fierce Guardianship", "Deflecting Swat",
  "Deadly Rollick", "Flawless Maneuver",
  "Anguished Unmaking", "Despark",
  "Aetherflux Reservoir", "Isochron Scepter",
  "Grand Abolisher", "Drannith Magistrate",
  "Oracle of Mul Daya", "Bloom Tender",
  "Delighted Halfling",
  "Damn", "Feed the Swarm",
  "Deadly Dispute", "Village Rites",
  "Night's Whisper", "Sign in Blood",
  "Return of the Wildspeaker", "Rishkar's Expertise",
  "Beast Whisperer", "Guardian Project",
  "Garruk's Uprising", "Elemental Bond",
  "Harmonize", "Painful Truths",
  "Herald's Horn", "Urza's Incubator",

  // Signets and talismans
  "Azorius Signet", "Dimir Signet", "Rakdos Signet",
  "Gruul Signet", "Selesnya Signet", "Orzhov Signet",
  "Izzet Signet", "Golgari Signet", "Boros Signet", "Simic Signet",
  "Talisman of Progress", "Talisman of Dominance",
  "Talisman of Indulgence", "Talisman of Creativity",
  "Talisman of Conviction", "Talisman of Hierarchy",

  // Chaos Orb relatives
  "Chaos Orb",

  // Other classics
  "Counterspell", "Lightning Bolt", "Giant Growth", "Healing Salve",
  "Ancestral Recall", "Dark Ritual",
  "Disenchant", "Terror", "Naturalize",
  "Wrath of God", "Armageddon",
  "Swords to Plowshares", "Balance",
  "Crusade", "Bad Moon",
  "Howling Mine", "Ivory Tower",
  "Maze of Ith", "Library of Alexandria",
  "Demonic Hordes", "Lord of the Pit",
  "Mahamoti Djinn", "Force of Nature",
];
